apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: tektoncd-nodejs-tutorial-build-taskrun-
  namespace: nodejs-tekton
spec:
  serviceAccount: pipeline
  inputs:
    resources:
      - name: tektoncd-nodejs-tutorial-resources
        resourceRef:
          name: tektoncd-nodejs-tutorial-resources
  taskRef:
    name: tektoncd-nodejs-tutorial-task
